home_page:
    path:     /
    defaults: { _controller: "ReservationBundle:Reservation:index" }
    methods:  GET

get_info:
    path:     /getInfoAction
    defaults: { _controller: "ReservationBundle:Reservation:getInfo" }
    methods:  [GET, POST]

verifie_reservation:
    path:     /verif-date-reservation
    defaults: { _controller: "ReservationBundle:Reservation:verificationBillet" }
    methods:  [GET, POST]