user_index:
    path:     /index
    defaults: { _controller: "ReservationBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "ReservationBundle:User:show" }
    methods:  GET

user_new:
    path:     /test
    defaults: { _controller: "ReservationBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReservationBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReservationBundle:User:delete" }
    methods:  DELETE
