<?php

namespace ReservationBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Une methode pour recupérer les billets à partir id de l'utilisateurs
     * @param $user_id
     * @return array
     */
    public function  getBilletByUserId($user_id)
    {

        $qb = $this->createQueryBuilder('r');
        $qb->select('r')
            ->where('r.user = :user')
            ->setParameter('user',$user_id);

        return $qb->getQuery()->getResult();
    }
}
