<?php

namespace ReservationBundle\Repository;

/**
 * StatistiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatistiqueRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Une methode qui permet de vérifier la disponibilité de la date selectionnez
     * par le visiteur
     * @param $date
     * @return array
     */
    public function verifieDisponibiliteByDate($date){

        $qb = $this->createQueryBuilder('s');
        $qb->select('s.nbBilletVendu')
            ->where('s.date = :date')
            ->setParameter('date',$date);

        return $qb->getQuery()->getScalarResult();
    }

    /**
     *  Mise à jour des billets vendu dans le statistique
     * @param $date
     */
    public function updateStatByDate($date,$nombreBillet){
        $qb = $this->createQueryBuilder('s');
        $qb->update()
            ->set('s.nbBilletVendu', '?1')
            ->setParameter(1, $qb->expr()->literal($nombreBillet))
            ->where('s.date = ?2')
            ->setParameter(2, $date->format('Y-m-d'));
        return $qb->getQuery()->getSingleScalarResult();
    }
}











